import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1784139253877 implements MigrationInterface {
    name = 'Init1784139253877'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "competitions" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "logoUrl" character varying, "colorPrimary" character varying(7), "colorSecondary" character varying(7), "isActive" boolean NOT NULL DEFAULT true, "type" character varying, "region" character varying, CONSTRAINT "UQ_4d84119d1fee0c7af34d211464a" UNIQUE ("slug"), CONSTRAINT "PK_ef273910798c3a542b475e75c7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "seasons" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "competition_id" integer NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "year" integer, "startDate" date, "endDate" date, "status" character varying NOT NULL DEFAULT 'planned', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_cb8ed53b5fe109dcd4a4449ec9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "venues" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "address" character varying, "city" character varying, "village" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_9fd71efb7abb246a69847399d14" UNIQUE ("slug"), CONSTRAINT "PK_cb0f885278d12384eb7a81818be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."match_officials_role_enum" AS ENUM('main_referee', 'assistant_referee', 'second_assistant_referee', 'timekeeper', 'delegate')`);
        await queryRunner.query(`CREATE TABLE "match_officials" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "match_id" integer NOT NULL, "fullName" character varying NOT NULL, "role" "public"."match_officials_role_enum" NOT NULL, CONSTRAINT "PK_d0e3e3abc843aa2b041e9c624a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."matches_status_enum" AS ENUM('scheduled', 'live', 'finished', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "matches" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tournament_id" integer NOT NULL, "home_team_id" integer NOT NULL, "away_team_id" integer NOT NULL, "venue_id" integer, "match_datetime" TIMESTAMP, "round" character varying, "status" "public"."matches_status_enum" NOT NULL DEFAULT 'scheduled', "home_score" integer NOT NULL DEFAULT '0', "away_score" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_8a22c7b2e0828988d51256117f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."match_events_eventtype_enum" AS ENUM('goal', 'own_goal', 'penalty_goal', 'penalty_missed', 'yellow_card', 'second_yellow_card', 'red_card', 'substitution', 'red_ball', 'match_started', 'match_paused', 'match_resumed', 'half_finished', 'second_half_started', 'match_finished', 'protocol_signed')`);
        await queryRunner.query(`CREATE TABLE "match_events" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "match_id" integer NOT NULL, "team_id" integer NOT NULL, "player_id" integer, "eventType" "public"."match_events_eventtype_enum" NOT NULL, "minute" integer, "addedMinute" integer, "description" text, "assist_player_id" integer, "secondary_player_id" integer, "half" integer, "second" integer, "client_event_id" character varying, "is_cancelled" boolean NOT NULL DEFAULT false, "goal_value" integer NOT NULL DEFAULT '1', CONSTRAINT "UQ_4cd38bfa85700d171e0c5fca639" UNIQUE ("client_event_id"), CONSTRAINT "PK_34160ac79fb420bdc42a6b24854" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roles_code_enum" AS ENUM('super_admin', 'admin', 'referee', 'captain', 'player', 'user')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "code" "public"."roles_code_enum" NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c" UNIQUE ("code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_auth_accounts_provider_enum" AS ENUM('local', 'vk')`);
        await queryRunner.query(`CREATE TABLE "user_auth_accounts" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "provider" "public"."user_auth_accounts_provider_enum" NOT NULL, "providerUserId" character varying, "login" character varying, "passwordHash" character varying, CONSTRAINT "PK_3d8dd4e6415b3993d0beed06c7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_auth_accounts_provider_external_id" ON "user_auth_accounts" ("provider", "providerUserId") WHERE "providerUserId" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_auth_accounts_provider_login" ON "user_auth_accounts" ("provider", "login") WHERE "login" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying, "username" character varying NOT NULL, "passwordHash" character varying, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "middleName" character varying, "avatarUrl" character varying, "phone" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."players_preferredfoot_enum" AS ENUM('left', 'right', 'both')`);
        await queryRunner.query(`CREATE TYPE "public"."players_position_enum" AS ENUM('goalkeeper', 'defender', 'midfielder', 'forward')`);
        await queryRunner.query(`CREATE TABLE "players" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "middleName" character varying, "slug" character varying NOT NULL, "user_id" integer, "birthDate" date, "photoUrl" character varying, "preferredFoot" "public"."players_preferredfoot_enum", "position" "public"."players_position_enum", "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_7310cf1fe0f6e1b70560e5d5a6c" UNIQUE ("slug"), CONSTRAINT "UQ_ba3575d2fbe71fab7155366235e" UNIQUE ("user_id"), CONSTRAINT "REL_ba3575d2fbe71fab7155366235" UNIQUE ("user_id"), CONSTRAINT "PK_de22b8fdeee0c33ab55ae71da3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."team_players_position_enum" AS ENUM('goalkeeper', 'defender', 'midfielder', 'forward')`);
        await queryRunner.query(`CREATE TABLE "team_players" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "team_id" integer NOT NULL, "player_id" integer NOT NULL, "shirtNumber" integer, "position" "public"."team_players_position_enum", "isCaptain" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "joinedAt" date, "leftAt" date, CONSTRAINT "PK_e5cc65b0865477e94f8c08af216" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "standings" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tournament_id" integer NOT NULL, "team_id" integer NOT NULL, "position" integer, "played" integer NOT NULL DEFAULT '0', "wins" integer NOT NULL DEFAULT '0', "draws" integer NOT NULL DEFAULT '0', "losses" integer NOT NULL DEFAULT '0', "goalsFor" integer NOT NULL DEFAULT '0', "goalsAgainst" integer NOT NULL DEFAULT '0', "goalDifference" integer NOT NULL DEFAULT '0', "points" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_a8d990b7004d5eeaefb83c8b6e3" UNIQUE ("tournament_id", "team_id"), CONSTRAINT "PK_ca695befaab9b01d05dd453dbdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teams" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "shortName" character varying, "slug" character varying NOT NULL, "description" text, "logoUrl" character varying, "primaryColor" character varying(7), "secondaryColor" character varying(7), "city" character varying, "village" character varying, "foundedYear" integer, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_de8536da4945fe980f4a61900d3" UNIQUE ("slug"), CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tournament_teams_status_enum" AS ENUM('active', 'withdrawn', 'disqualified')`);
        await queryRunner.query(`CREATE TABLE "tournament_teams" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tournament_id" integer NOT NULL, "team_id" integer NOT NULL, "groupName" character varying, "seedNumber" integer, "status" "public"."tournament_teams_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_e5e9835d1cc7678bc6f8b9cb4cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tournaments_type_enum" AS ENUM('league', 'cup', 'friendly', 'superCup')`);
        await queryRunner.query(`CREATE TYPE "public"."tournaments_format_enum" AS ENUM('round_robin', 'knockout', 'mixed')`);
        await queryRunner.query(`CREATE TYPE "public"."tournaments_status_enum" AS ENUM('planned', 'active', 'finished', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "tournaments" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "season_id" integer NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "type" "public"."tournaments_type_enum", "format" "public"."tournaments_format_enum", "startDate" date, "endDate" date, "status" "public"."tournaments_status_enum" NOT NULL DEFAULT 'planned', "colorPrimary" character varying(7), "colorSecondary" character varying(7), "logoUrl" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_6d5d129da7a80cf99e8ad4833a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player_transfers" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "player_id" integer NOT NULL, "from_team_id" integer NOT NULL, "to_team_id" integer NOT NULL, "from_team_player_id" integer NOT NULL, "to_team_player_id" integer NOT NULL, "transfer_date" date NOT NULL, "comment" text, "created_by_user_id" integer NOT NULL, CONSTRAINT "PK_d9bc80d4ceffff07eb1df0863e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."player_tournament_stats_suspension_reason_enum" AS ENUM('four_yellow_cards', 'red_card', 'second_yellow_card')`);
        await queryRunner.query(`CREATE TABLE "player_tournament_stats" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "tournament_id" integer NOT NULL, "team_id" integer NOT NULL, "player_id" integer NOT NULL, "yellow_cards" integer NOT NULL DEFAULT '0', "red_cards" integer NOT NULL DEFAULT '0', "second_yellow_cards" integer NOT NULL DEFAULT '0', "suspensions_served" integer NOT NULL DEFAULT '0', "is_suspended" boolean NOT NULL DEFAULT false, "suspended_until_match_id" integer, "suspension_reason" "public"."player_tournament_stats_suspension_reason_enum", CONSTRAINT "UQ_b210f0ccaf002b21e11438ae395" UNIQUE ("tournament_id", "team_id", "player_id"), CONSTRAINT "PK_ade290075bf901ca3ba859f443c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "news" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "slug" character varying NOT NULL, "excerpt" text, "content" text NOT NULL, "coverUrl" character varying, "status" character varying NOT NULL DEFAULT 'draft', "publishedAt" TIMESTAMP, CONSTRAINT "UQ_d09152c44881b7620e12d6df099" UNIQUE ("slug"), CONSTRAINT "PK_39a43dfcb6007180f04aff2357e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."red_ball_status_enum" AS ENUM('active', 'completed_by_goal', 'completed_by_time', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "match_red_ball_activations" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "match_id" integer NOT NULL, "team_id" integer NOT NULL, "activated_half" integer NOT NULL, "activated_second" integer NOT NULL, "duration_seconds" integer NOT NULL DEFAULT '120', "status" "public"."red_ball_status_enum" NOT NULL DEFAULT 'active', "completed_half" integer, "completed_second" integer, "completed_by_event_id" integer, CONSTRAINT "PK_563e3f99a4729f71a7013073cdc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "match_rosters" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "match_id" integer NOT NULL, "team_id" integer NOT NULL, "is_approved" boolean NOT NULL DEFAULT false, "is_submitted" boolean NOT NULL DEFAULT false, "submitted_at" TIMESTAMP, "submitted_by_user_id" integer, "approved_at" TIMESTAMP, "approved_by_user_id" integer, CONSTRAINT "UQ_5f8178e33af421d36dcccd78f14" UNIQUE ("match_id", "team_id"), CONSTRAINT "PK_05a6ad356b7f7c11977e7d5d3ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."match_roster_players_position_enum" AS ENUM('goalkeeper', 'defender', 'midfielder', 'forward')`);
        await queryRunner.query(`CREATE TABLE "match_roster_players" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "match_roster_id" integer NOT NULL, "player_id" integer NOT NULL, "team_player_id" integer, "shirt_number" integer, "position" "public"."match_roster_players_position_enum", "is_captain" boolean NOT NULL DEFAULT false, "was_allowed" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_e69df37f0652f502ecee5f4af12" UNIQUE ("match_roster_id", "player_id"), CONSTRAINT "PK_1b6166dc6185b9a3ea913d4b3d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."match_service_sessions_status_enum" AS ENUM('not_started', 'first_half', 'half_time', 'second_half', 'paused', 'event_recording', 'finished', 'protocol_signed')`);
        await queryRunner.query(`CREATE TYPE "public"."match_service_sessions_previous_status_enum" AS ENUM('not_started', 'first_half', 'half_time', 'second_half', 'paused', 'event_recording', 'finished', 'protocol_signed')`);
        await queryRunner.query(`CREATE TABLE "match_service_sessions" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "match_id" integer NOT NULL, "status" "public"."match_service_sessions_status_enum" NOT NULL DEFAULT 'not_started', "previous_status" "public"."match_service_sessions_previous_status_enum", "current_half" integer NOT NULL DEFAULT '1', "elapsed_seconds" integer NOT NULL DEFAULT '0', "started_at" TIMESTAMP, "paused_at" TIMESTAMP, "finished_at" TIMESTAMP, "home_score" integer NOT NULL DEFAULT '0', "away_score" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_a4b4c1c79a46747a4ed86254a26" UNIQUE ("match_id"), CONSTRAINT "REL_a4b4c1c79a46747a4ed86254a2" UNIQUE ("match_id"), CONSTRAINT "PK_51d8277fe92c41146f5335bae7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("usersId" integer NOT NULL, "rolesId" integer NOT NULL, CONSTRAINT "PK_38ffcfb865fc628fa337d9a0d4f" PRIMARY KEY ("usersId", "rolesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_99b019339f52c63ae615358738" ON "user_roles" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13380e7efec83468d73fc37938" ON "user_roles" ("rolesId") `);
        await queryRunner.query(`ALTER TABLE "seasons" ADD CONSTRAINT "FK_47b4c52ec141bc0ef8b7106777e" FOREIGN KEY ("competition_id") REFERENCES "competitions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_officials" ADD CONSTRAINT "FK_90041bfec36da0b707be80a6dbd" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_cb90abceb14ab1b73e92823acce" FOREIGN KEY ("venue_id") REFERENCES "venues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_e457f057d971e464c1ebf6378c5" FOREIGN KEY ("away_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_bb25f11ea6fa78b344a68923769" FOREIGN KEY ("home_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_d0fb132a9b17b5801b916662147" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_events" ADD CONSTRAINT "FK_5bd1e02201ebf85de3ba5b70a83" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_events" ADD CONSTRAINT "FK_57fdadec2ad1ce3e3cdfaff023b" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_events" ADD CONSTRAINT "FK_482e23aeaaa3485fdb0b573f8ec" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_events" ADD CONSTRAINT "FK_7b563e2138640addeaaa02695bc" FOREIGN KEY ("assist_player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_events" ADD CONSTRAINT "FK_c8b92c2650353037bbed9ceb658" FOREIGN KEY ("secondary_player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_auth_accounts" ADD CONSTRAINT "FK_1a080f9e8ed68453e05000389da" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_ba3575d2fbe71fab7155366235e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_players" ADD CONSTRAINT "FK_187fdfeb2ca268cf6b93e89ce12" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_players" ADD CONSTRAINT "FK_d1c561e231a8067e2f7a403426c" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "standings" ADD CONSTRAINT "FK_eb4f41b04bdfa39dfb92cdf9410" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "standings" ADD CONSTRAINT "FK_3bbd65ccfcbe4e9108b41528b65" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_teams" ADD CONSTRAINT "FK_1a8faed6cf5e1669d40b3a8b762" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournament_teams" ADD CONSTRAINT "FK_2e3297dc33a4087af1c1bf4c645" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tournaments" ADD CONSTRAINT "FK_4018458373e2a9e8a8c54ccfbb5" FOREIGN KEY ("season_id") REFERENCES "seasons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transfers" ADD CONSTRAINT "FK_228ace3ed756b06fba2ba7fb1f2" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transfers" ADD CONSTRAINT "FK_865c14eccf0873684f909e8011f" FOREIGN KEY ("from_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transfers" ADD CONSTRAINT "FK_6f6a1a614d9a3dfcf69e68c28e6" FOREIGN KEY ("to_team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transfers" ADD CONSTRAINT "FK_6615627663ef5fb5aacbe716409" FOREIGN KEY ("from_team_player_id") REFERENCES "team_players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transfers" ADD CONSTRAINT "FK_f19ee1a9bcd820ed96f0aa58897" FOREIGN KEY ("to_team_player_id") REFERENCES "team_players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_transfers" ADD CONSTRAINT "FK_a7955f61012a9dd019371554a93" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_tournament_stats" ADD CONSTRAINT "FK_81f9a75ad7a65013e480b4c2b71" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_tournament_stats" ADD CONSTRAINT "FK_34c650626a95b72ec725d43bd85" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_tournament_stats" ADD CONSTRAINT "FK_e5402bf493b60e8a8da0f5f45ad" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_tournament_stats" ADD CONSTRAINT "FK_8f7a4e771333ab0fcc3ad9601f2" FOREIGN KEY ("suspended_until_match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_red_ball_activations" ADD CONSTRAINT "FK_68f274368d1abe3f3c049d6bb65" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_red_ball_activations" ADD CONSTRAINT "FK_408e765aa3f1f622f2fcaa2bbcb" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_rosters" ADD CONSTRAINT "FK_228b50a669221ce56c58b73711b" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_rosters" ADD CONSTRAINT "FK_8ea96a71cc8f6d691bc2813c8b6" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_rosters" ADD CONSTRAINT "FK_4dedfe390dce80dfe3658e52426" FOREIGN KEY ("submitted_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_rosters" ADD CONSTRAINT "FK_06fc5cf5263b5c3d49b06990d33" FOREIGN KEY ("approved_by_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_roster_players" ADD CONSTRAINT "FK_30eee677f53ef5e2a2cce2100c0" FOREIGN KEY ("match_roster_id") REFERENCES "match_rosters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_roster_players" ADD CONSTRAINT "FK_4012345e6b089d59106b38ddc9c" FOREIGN KEY ("player_id") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_roster_players" ADD CONSTRAINT "FK_fcec380470fccd8ac20e0d5f511" FOREIGN KEY ("team_player_id") REFERENCES "team_players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_service_sessions" ADD CONSTRAINT "FK_a4b4c1c79a46747a4ed86254a26" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_99b019339f52c63ae6153587380" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_13380e7efec83468d73fc37938e" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_13380e7efec83468d73fc37938e"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_99b019339f52c63ae6153587380"`);
        await queryRunner.query(`ALTER TABLE "match_service_sessions" DROP CONSTRAINT "FK_a4b4c1c79a46747a4ed86254a26"`);
        await queryRunner.query(`ALTER TABLE "match_roster_players" DROP CONSTRAINT "FK_fcec380470fccd8ac20e0d5f511"`);
        await queryRunner.query(`ALTER TABLE "match_roster_players" DROP CONSTRAINT "FK_4012345e6b089d59106b38ddc9c"`);
        await queryRunner.query(`ALTER TABLE "match_roster_players" DROP CONSTRAINT "FK_30eee677f53ef5e2a2cce2100c0"`);
        await queryRunner.query(`ALTER TABLE "match_rosters" DROP CONSTRAINT "FK_06fc5cf5263b5c3d49b06990d33"`);
        await queryRunner.query(`ALTER TABLE "match_rosters" DROP CONSTRAINT "FK_4dedfe390dce80dfe3658e52426"`);
        await queryRunner.query(`ALTER TABLE "match_rosters" DROP CONSTRAINT "FK_8ea96a71cc8f6d691bc2813c8b6"`);
        await queryRunner.query(`ALTER TABLE "match_rosters" DROP CONSTRAINT "FK_228b50a669221ce56c58b73711b"`);
        await queryRunner.query(`ALTER TABLE "match_red_ball_activations" DROP CONSTRAINT "FK_408e765aa3f1f622f2fcaa2bbcb"`);
        await queryRunner.query(`ALTER TABLE "match_red_ball_activations" DROP CONSTRAINT "FK_68f274368d1abe3f3c049d6bb65"`);
        await queryRunner.query(`ALTER TABLE "player_tournament_stats" DROP CONSTRAINT "FK_8f7a4e771333ab0fcc3ad9601f2"`);
        await queryRunner.query(`ALTER TABLE "player_tournament_stats" DROP CONSTRAINT "FK_e5402bf493b60e8a8da0f5f45ad"`);
        await queryRunner.query(`ALTER TABLE "player_tournament_stats" DROP CONSTRAINT "FK_34c650626a95b72ec725d43bd85"`);
        await queryRunner.query(`ALTER TABLE "player_tournament_stats" DROP CONSTRAINT "FK_81f9a75ad7a65013e480b4c2b71"`);
        await queryRunner.query(`ALTER TABLE "player_transfers" DROP CONSTRAINT "FK_a7955f61012a9dd019371554a93"`);
        await queryRunner.query(`ALTER TABLE "player_transfers" DROP CONSTRAINT "FK_f19ee1a9bcd820ed96f0aa58897"`);
        await queryRunner.query(`ALTER TABLE "player_transfers" DROP CONSTRAINT "FK_6615627663ef5fb5aacbe716409"`);
        await queryRunner.query(`ALTER TABLE "player_transfers" DROP CONSTRAINT "FK_6f6a1a614d9a3dfcf69e68c28e6"`);
        await queryRunner.query(`ALTER TABLE "player_transfers" DROP CONSTRAINT "FK_865c14eccf0873684f909e8011f"`);
        await queryRunner.query(`ALTER TABLE "player_transfers" DROP CONSTRAINT "FK_228ace3ed756b06fba2ba7fb1f2"`);
        await queryRunner.query(`ALTER TABLE "tournaments" DROP CONSTRAINT "FK_4018458373e2a9e8a8c54ccfbb5"`);
        await queryRunner.query(`ALTER TABLE "tournament_teams" DROP CONSTRAINT "FK_2e3297dc33a4087af1c1bf4c645"`);
        await queryRunner.query(`ALTER TABLE "tournament_teams" DROP CONSTRAINT "FK_1a8faed6cf5e1669d40b3a8b762"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP CONSTRAINT "FK_3bbd65ccfcbe4e9108b41528b65"`);
        await queryRunner.query(`ALTER TABLE "standings" DROP CONSTRAINT "FK_eb4f41b04bdfa39dfb92cdf9410"`);
        await queryRunner.query(`ALTER TABLE "team_players" DROP CONSTRAINT "FK_d1c561e231a8067e2f7a403426c"`);
        await queryRunner.query(`ALTER TABLE "team_players" DROP CONSTRAINT "FK_187fdfeb2ca268cf6b93e89ce12"`);
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_ba3575d2fbe71fab7155366235e"`);
        await queryRunner.query(`ALTER TABLE "user_auth_accounts" DROP CONSTRAINT "FK_1a080f9e8ed68453e05000389da"`);
        await queryRunner.query(`ALTER TABLE "match_events" DROP CONSTRAINT "FK_c8b92c2650353037bbed9ceb658"`);
        await queryRunner.query(`ALTER TABLE "match_events" DROP CONSTRAINT "FK_7b563e2138640addeaaa02695bc"`);
        await queryRunner.query(`ALTER TABLE "match_events" DROP CONSTRAINT "FK_482e23aeaaa3485fdb0b573f8ec"`);
        await queryRunner.query(`ALTER TABLE "match_events" DROP CONSTRAINT "FK_57fdadec2ad1ce3e3cdfaff023b"`);
        await queryRunner.query(`ALTER TABLE "match_events" DROP CONSTRAINT "FK_5bd1e02201ebf85de3ba5b70a83"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_d0fb132a9b17b5801b916662147"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_bb25f11ea6fa78b344a68923769"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_e457f057d971e464c1ebf6378c5"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_cb90abceb14ab1b73e92823acce"`);
        await queryRunner.query(`ALTER TABLE "match_officials" DROP CONSTRAINT "FK_90041bfec36da0b707be80a6dbd"`);
        await queryRunner.query(`ALTER TABLE "seasons" DROP CONSTRAINT "FK_47b4c52ec141bc0ef8b7106777e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13380e7efec83468d73fc37938"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99b019339f52c63ae615358738"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "match_service_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."match_service_sessions_previous_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."match_service_sessions_status_enum"`);
        await queryRunner.query(`DROP TABLE "match_roster_players"`);
        await queryRunner.query(`DROP TYPE "public"."match_roster_players_position_enum"`);
        await queryRunner.query(`DROP TABLE "match_rosters"`);
        await queryRunner.query(`DROP TABLE "match_red_ball_activations"`);
        await queryRunner.query(`DROP TYPE "public"."red_ball_status_enum"`);
        await queryRunner.query(`DROP TABLE "news"`);
        await queryRunner.query(`DROP TABLE "player_tournament_stats"`);
        await queryRunner.query(`DROP TYPE "public"."player_tournament_stats_suspension_reason_enum"`);
        await queryRunner.query(`DROP TABLE "player_transfers"`);
        await queryRunner.query(`DROP TABLE "tournaments"`);
        await queryRunner.query(`DROP TYPE "public"."tournaments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tournaments_format_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tournaments_type_enum"`);
        await queryRunner.query(`DROP TABLE "tournament_teams"`);
        await queryRunner.query(`DROP TYPE "public"."tournament_teams_status_enum"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP TABLE "standings"`);
        await queryRunner.query(`DROP TABLE "team_players"`);
        await queryRunner.query(`DROP TYPE "public"."team_players_position_enum"`);
        await queryRunner.query(`DROP TABLE "players"`);
        await queryRunner.query(`DROP TYPE "public"."players_position_enum"`);
        await queryRunner.query(`DROP TYPE "public"."players_preferredfoot_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_auth_accounts_provider_login"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_auth_accounts_provider_external_id"`);
        await queryRunner.query(`DROP TABLE "user_auth_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."user_auth_accounts_provider_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_code_enum"`);
        await queryRunner.query(`DROP TABLE "match_events"`);
        await queryRunner.query(`DROP TYPE "public"."match_events_eventtype_enum"`);
        await queryRunner.query(`DROP TABLE "matches"`);
        await queryRunner.query(`DROP TYPE "public"."matches_status_enum"`);
        await queryRunner.query(`DROP TABLE "match_officials"`);
        await queryRunner.query(`DROP TYPE "public"."match_officials_role_enum"`);
        await queryRunner.query(`DROP TABLE "venues"`);
        await queryRunner.query(`DROP TABLE "seasons"`);
        await queryRunner.query(`DROP TABLE "competitions"`);
    }

}
